export const businessPermissions = [
  ['customers:read', 'View customers'],
  ['customers:write', 'Create and update customers'],
  ['measurements:read', 'View measurements'],
  ['measurements:write', 'Create measurement revisions'],
  ['orders:read', 'View orders'],
  ['orders:write', 'Create orders'],
  ['orders:transition', 'Advance order workflow'],
  ['payments:read', 'View payments'],
  ['payments:write', 'Record payments'],
  ['notifications:read', 'View customer notification delivery history'],
  ['reports:read', 'View business reports'],
  ['audit:read', 'View business audit history'],
  ['staff:manage', 'Manage business staff'],
  ['settings:manage', 'Manage business settings'],
  ['subscriptions:read', 'View subscription and payment history'],
  ['subscriptions:manage', 'Request plans and submit subscription payments'],
] as const;

export const platformPermissions = [
  ['platform:businesses:read', 'View all businesses'],
  ['platform:businesses:manage', 'Create, activate and suspend businesses'],
  ['platform:staff:manage', 'Manage platform staff and their explicit grants'],
  ['platform:audit:read', 'View platform-wide audit history'],
  ['platform:system:health', 'View platform system health'],
  ['platform:subscriptions:read', 'View subscription dashboard and business subscriptions'],
  ['platform:plans:manage', 'Manage subscription plans'],
  ['platform:payments:review', 'Review subscription payment submissions'],
  ['platform:subscriptions:manage', 'Manage business subscription lifecycle'],
  ['platform:billing:settings', 'Manage billing instructions and settings'],
  ['platform:reports:read', 'View subscription and payment reports'],
] as const;
