ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_CREATED';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_UPDATED';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'MEASUREMENT_APPENDED';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAYMENT_SUBMITTED';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAYMENT_UNDER_REVIEW';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAYMENT_APPROVED';
ALTER TYPE "WhatsAppNotificationKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAYMENT_REJECTED';

CREATE TABLE "WhatsAppNotificationScanCursor" (
  "id" VARCHAR(80) NOT NULL,
  "lastId" UUID,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "WhatsAppNotificationScanCursor_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "BusinessConfiguration"
  ADD COLUMN "itemTypes" JSONB;
